Define Raven version as a global variable.
CSHS-CWRA/RavenHydroFramework pull request #17
Opened 2023-11-02 18:23 UTC by huard

Create a shared library that can be imported from Python to expose the version.

### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #16
- [ ] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

 * Add libraven.cpp used to compile a shared library that can be imported from python.

Now we can do
```
$ make libraven
$ python
>>> import libraven
>>> libraven.__version__
'3.7.1'
```

### Does this PR introduce a breaking change?

 * No, but I'm a cmake noob, so I probably messed something up.

2023-11-02 18:30 UTC, Zeitsperre approved these changes
Wow! For the time being, we'd need to port this to `raven-hydro` as well, but this is a great first step towards a true wrapping mechanism for Python. Well done!

2023-11-03 14:18 UTC, analytophile requested changes
could we 
1) move the libraven.cpp to a subfolder of src/ to indicate it is an auxiliary part of the source code?
2) make the python connection activate with a switch in the Makefile rather than as the default setting?

This removes the requirement of pybind11.h library access.

2023-11-03 15:37 UTC, huard commented
Done.

2023-12-20 15:06 UTC, analytophile approved these changes

2023-12-20 15:06 UTC, merged